### ISSUE TITLE
Doesn't show sql if all queries executed using one cursor

### ISSUE THREAD

**Issue by Lagovas** [django-debug-toolbar/django-debug-toolbar#638]
If you have Manager
```
class ArticleManager(models.Manager):
    def __init__(self, *args, **kwargs):
        super(ArticleManager, self).__init__(*args, **kwargs)
        self.cursor = connection.cursor()
```
and than use self.cursor for executing queries, they won't display on sql panel.
But if always use new cursor ```cursor = connection.cursor()``` then all is fine.

**Comment by aaugustin** [comment]
If `connection.cursor()` is called after the toolbar's request middleware is run, queries made with this cursor will be recorded, otherwise they won't.

In your case it appears the cursor is created once for the entire lifetime of the Django process. That cannot work reliably. I don't think the toolbar should accomodate this.
