### ISSUE TITLE
RemovedInDjango18Warning in Django 1.7

### ISSUE THREAD

**Issue by epicserve** [django-debug-toolbar/django-debug-toolbar#648]
When running my tests I'm getting.

```
RemovedInDjango18Warning: 'The `cycle` template tag is changing to escape its arguments;
the non-autoescaping version is deprecated. Load it from the `future` tag library to start
using the new behavior.
````

**Comment by aaugustin** [comment]
I checked the source code:

- `{% load cycle from future %}` is never used
- `{% cycle 'djDebugOdd' 'djDebugEven' %}` is the only use of the cycle tag

Since it's only called on fixed strings, escaping has no effect and we don't need to make any changes for Django 1.8. There's a spurious warning on 1.7 but it will go away on 1.8.

Making our own version of the cycle tag or breaking 1.4 seem more inconvenient than having a warning, so my suggestion is not to do anything.
