### ISSUE TITLE
default JQuery isn't supported in IE 8

### ISSUE THREAD

**Issue by rtpg** [django-debug-toolbar/django-debug-toolbar#676]
The default JQuery setting (found [here](https://github.com/django-debug-toolbar/django-debug-toolbar/blob/d9d8e3afdc26080ee8b17828dce045314d968d6e/debug_toolbar/settings.py#L24)) drops IE8 support, but the toolbar itself works fine if a proper jquery is used though.  Would recommend swapping out for jquery 1.11.2 (functionally identical but works with IE8)

**Comment by aaugustin** [comment]
The toolbar being a development tool, it seems reasonable to me to use the latest released version of jQuery. If you want to use jQuery 1.11.2, you can change that URL in your project's settings.

Since the toolbar only provides browser-independent debugging info and since IE8 isn't a particularly good browser for doing web development in general, supporting IE8 isn't a goal.

**Comment by rtpg** [comment]
That's reasonable, but the issue comes from the fact that the jquery init process breaks halfway through, effectively breaking the global `JQuery` and `$` objects, causing all sorts of JS breakage apart from the toolbar.

 If someone is maintaining a Django app that requires IE8 support and uses the toolbar, they effectively have to turn off the toolbar to check the rest of the app. I realise IE support is low on the list, and the settings fix is one time.

Anyways, for anyone who lands here through Google or whatnot, I set this in my settings:
```
DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': '//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js',
}
```
