### ISSUE TITLE
When GZip middleware enabled, auto-insert after it

### ISSUE THREAD

**Issue by natevw** [django-debug-toolbar/django-debug-toolbar#681]
The current setup code has one routine that simply prepends itself into `settings.MIDDLEWARE_CLASSES` and another that checks to make sure itself is after GZip middleware in the list.

This makes it hard to use the toolbar via simply adding it to `settings.INSTALLED_APPS` in a localsettings context — instead you must override the whole of `MIDDLEWARE_CLASSES`. If the toolbar is smart enough to know where it *should* be placed, couldn't it just place itself there in the first place?

**Comment by natevw** [comment]
One workaround I found for this is to just leave the toolbar's *middleware* line in default project settings. The trick is that Django will simply pass over it *unless* the toolbar is in `settings.INSTALLED_APPS`, which is easy to append to in local settings.

Put another way: by always having the middleware *listed* in its proper place, you can still enable/disable the "easy way" that's possible when no GZip is used.

**Comment by aaugustin** [comment]
The problem is -- the toolbar isn't smart enough to know where it should be placed. It can determine that it's incorrectly placed in some cases, but that's less complicated.

The correct position depends on which middleware the developer wants to include in the profiling.

If you want to suggest a specific algorithm for inserting the toolbar's middleware in the automatic setup, or even better, provide a patch, that would be interesting. In the meantime I'm going to close the ticket because it doesn't contain an actionable proposal.
