### ISSUE TITLE
Templates displayed after page load are ignored

### ISSUE THREAD

**Issue by matthew-hodgins** [django-debug-toolbar/django-debug-toolbar#730]
Environment:
django-debug-toolbar==1.3.2
Django==1.6.5

I have a page with tabs, structured like this:

	<div id="test-tabs">
		<ul>
			<li><a href="get_tab1">Tab 1</a></li>
			<li><a href="get_tab1">Tab 2</a></li>
		</ul>
	</div>

get_tab1 and get_tab2 call views functions which themselves return templates and populate the tab. In my testing, the debug toolbar does not include any information for these templates.

Any ideas?

**Comment by tim-schilling** [comment]
This is a use case(AJAX requests) that the toolbar does not handle. You'll need to use a third party panel addition in order to get this data. Looks like https://github.com/recamshak/django-debug-panel and https://github.com/djsutho/django-debug-toolbar-request-history have options for supporting ajax.
