### ISSUE TITLE
Template source page is loading source from the filesystem, not django's memory.

### ISSUE THREAD

**Issue by bionikspoon** [django-debug-toolbar/django-debug-toolbar#755]
### Issue

The template source is being read from the file system.  In some cases this can be different then what Django actually uses.

### Debugging Scenario

Trying to troubleshoot issues with how my templates are rendering.  In my actual scenario, my dev server was not reloading on changes.  So when this tool shows my source to me from the file system, I'm getting misleading information.

### Improvement

It would be more useful to see how Django sees the templates.  I assume the source can be pulled in from Django's API in their raw form.  If not, maybe a note for us django beginners might be appropriate.

### Visual

Sample page of what I am talking about:  Template Source View

![screen shot 2015-09-18 at 14 04 00](https://cloud.githubusercontent.com/assets/5052422/9968495/6e3885b2-5e0e-11e5-9068-ec7d409c808d.png)

**Comment by tim-schilling** [comment]
```runserver``` won't reload when you change a template file. I believe it only reloads when a python file is updated. The toolbar does use Django's API for accessing templates' source code which is partly why you experience this.

I think the right decision is to make a note of this in the TemplatePanel documentation since the developer should know that he/she changed the file between the actual request and attempting to inspect that template.

**Comment by aaugustin** [comment]
Yes, I don't see a reasonable way to fix this. Django doesn't keep the template source around.
