### ISSUE TITLE
Django 1.9: missing template source on SQL panel

### ISSUE THREAD

**Issue by UncleVasya** [django-debug-toolbar/django-debug-toolbar#769]
How it looks with  Django 1.8:
![01](https://cloud.githubusercontent.com/assets/1286157/10886530/7623aee8-8193-11e5-90fe-fe3b913c8c47.PNG)

With Django 1.9 template source is missing:
![02](https://cloud.githubusercontent.com/assets/1286157/10886549/89a388d0-8193-11e5-87ac-b9aef365b5ae.PNG)

Both 1.9.a1 and 1.9.b1 affected.

**Comment by aaugustin** [comment]
The debug toolbar does some rather awful things with Django's internals, which changed in Django 1.9. Perhaps @prestontimmons could point us in the right direction?

**Comment by prestontimmons** [comment]
The error is in `debug_toolbar.utils.get_template_info()`. It finds the template instance in the stack frame, then calls `get_template_context()`. This fails since it uses the old `origin.reload()` API.

Can `get_template_info()` access the exception instead, maybe with `sys.exc_info()`? The exception should be annotated with the necessary debug information:

https://docs.djangoproject.com/en/dev/topics/templates/#contextual-line-information

The failing call happens in `debug_toolbar.panels.sql.tracking`. It looks like `debug_toolbar.panels.cache` has the same problem, also.

**Comment by sasha0** [comment]
Ok, prepared PR. @aaugustin do we need backward compatibility with Django < 1.9 ?

**Comment by aaugustin** [comment]
The toolbar must work with any supported version of Django, currently this starts at 1.8.

**Comment by sasha0** [comment]
@aaugustin ok, updated PR. Please take a look.

**Comment by sasha0** [comment]
@aaugustin I already updated PR - please take a look.

**Comment by aaugustin** [comment]
Thanks for your contribution.

I'm not maintaining the toolbar anymore. It's unlikely that I will review or commit non-trivial patches in the foreseeable future.

PS: perhaps https://github.com/django/django/pull/5984 is related?

**Comment by sasha0** [comment]
> I'm not maintaining the toolbar anymore. It's unlikely that I will review or commit non-trivial patches in the foreseeable future.

Could you please let me know about active project maintainers?

> PS: perhaps django/django#5984 is related?

Yes, but I need to re-check if this patch completely fixes the issue.

Thanks for the feedback.

**Comment by aaugustin** [comment]
Unfortunately, I don't have an answer to that question.

**Comment by tylerecouture** [comment]
I'm having this exact issue.  New to GIT and django-debug-toolbar.  Is there a way to get the toolbar with this commit/patch so the template inspection works?

**Comment by tim-schilling** [comment]
This commit is in the latest version of DDT on pip. It was included in v1.4. Try updating your version in your virtual environment.

**Comment by tylerecouture** [comment]
Yep, that was it. Thanks!
